### ISSUE TITLE
Autocomplete for class name

### ISSUE THREAD

**Issue by corporal9736** [clangd/vscode-clangd#210]
I'm not sure if this is a bug or feature requestion.

https://user-images.githubusercontent.com/60935688/125167743-94298f00-e1d4-11eb-8fd1-dcfe0597050f.mp4

I want autocompletion for class name as some class names are so long.
I didn't find a way to do that so far.
My system: wsl-ubuntu20.04
My configure for clangd extension:
```
"clangd.arguments": [
        "--background-index",
        "--compile-commands-dir=build",
        "-j=2",
        "--query-driver=/home/corporal/llvm/bin/clang++",
        "--clang-tidy",
        "--all-scopes-completion",
        "--completion-style=detailed",
        "--header-insertion=iwyu",
        "--pch-storage=memory",
        "--pretty",
      ],
"clangd.serverCompletionRanking": true
```
and the extension version is 0.1.11
clangd version is 13.0.0

**Comment by HighCommander4** [comment]
Completion for class names at global scope (as shown in your video) works for me.

Are you performing the keyboard shortcut to trigger completion (can't tell that from the video)?

**Comment by corporal9736** [comment]
Errr, I tried but Ctrl+Space also doesn't work for me.
I wonder where I can find the configuration for triggering completion. I want to check/change that.

**Comment by HighCommander4** [comment]
In the command palette, if you go to "Preferences: Open Keyboard Shotcuts", it looks like you can change the keybinding under `editor.action.triggerSuggest`.

If performing that keyboard shortcut does not successfully activate completion for you, the next step to investigate would be to share your clangd logs (select "clangd" from the dropdown in the Output view).

**Comment by corporal9736** [comment]
https://user-images.githubusercontent.com/60935688/125182696-ce317a00-e242-11eb-8b97-b9a3e431c9b5.mp4

[clangd_log.txt](https://github.com/clangd/vscode-clangd/files/6796340/clangd_log.txt)

Now I can successfully trigger the suggestion, but the result doesn't seems to be what I want, as you can see in the video.
And the txt file is the clangd log during the video. I cleaned the output view before I start typing.
And another problem is can I set this suggestion as auto, so I won't need to trigger that every time.
Thanks a lot!

**Comment by HighCommander4** [comment]
> Now I can successfully trigger the suggestion, but the result doesn't seems to be what I want, as you can see in the video.

Ok, so the editor is successfully sending a completion request to clangd, the results just don't include the completion item you're expecting.

So the issue is probably related to the specific code / library you are using.

The first thing to check would be, does clangd parse your code correctly? In this video, I see a diagnostic after you finish typing the type name (but I also see it has a typo in it). If you fix the typo, does the diagnostic go away (suggesting clangd resolves this symbol)? Are you able to use go-to-definition to navigate to the definition of `QGraphicsItem`?

> And another problem is can I set this suggestion as auto, so I won't need to trigger that every time.

I'm not sure. That's more a question about vscode than about clangd.

What I see in the [vscode documentation](https://code.visualstudio.com/docs/editor/intellisense) is:

> You can trigger IntelliSense in any editor window by typing `Ctrl+Space` or by typing a trigger character (such as the dot character (`.`) in JavaScript).

I don't see a mention of activating it on any character without a keyboard shortcut. Perhaps you can file a [vscode issue](https://github.com/microsoft/vscode/issues) asking if this is possible or if it can be added.

**Comment by corporal9736** [comment]
This class is an abstract class so it can't be used directly used. That's why the diagnostic shows.
I tried another class not abstract, the complete still not I want.
And when I move my mouse to the classname, it shows:
![image](https://user-images.githubusercontent.com/60935688/125183278-db049c80-e247-11eb-8f56-a3ff9b9d915a.png)
And I can go to the definition of both the abstract and non-abstract class. It worked well.
The library I'm using is Qt, I don't know if that might help.

**Comment by HighCommander4** [comment]
Hmm, interesting. I tried with a copy of Qt 5 that I had lying around on my system, and completion does offer me `QGraphicsItem` after including that header.

**Comment by corporal9736** [comment]
Let me check the other complete settings, I'm confused about what I should turn on/off. I think this happens because multiple completions are used...

**Comment by corporal9736** [comment]
Well, since I don't know what settings I have changed, I just uninstall and reinstall whole vscode. Now it works well... Thanks a lot!
