### ISSUE TITLE
successful build but error annotations

### ISSUE THREAD

**Issue by playgithub** [clangd/vscode-clangd#217]
## Env
OS: Linux
Compiler: c++
Project: cmake
clangd: 0.1.11

## Screenshot
![Screenshot_20210814_115125](https://user-images.githubusercontent.com/3665590/129433217-1566e310-b8b3-4613-9676-1e0473fd4df5.png)

## Description
The project is built successfully, but intellisense shows `No member named 'int64_t' in namespace 'std'`.
If add `#include <cstdint>`, it is fixed.
However it can be built without `#include <cstdint>`, what's the problem?

**Comment by HighCommander4** [comment]
It's hard to be sure without a complete example, but a wild guess: it might be a case of #45, i.e. the error is in a header "A" which implicitly relies on translation units including `<cstdint>` before they include "A". Clangd does not support such implicit dependencies, as it parses opened headers in a stand-alone fashion rather than in the context of some other file that includes them.

**Comment by playgithub** [comment]
> It's hard to be sure without a complete example, but a wild guess: it might be a case of [clangd/clangd#45](https://github.com/clangd/clangd/issues/45), i.e. the error is in a header "A" which implicitly relies on translation units including `<cstdint>` before they include "A". Clangd does not support such implicit dependencies, as it parses opened headers in a stand-alone fashion rather than in the context of some other file that includes them.

That's ok, explicit include is fine.
Thanks
