### ISSUE TITLE
Extension can not run on macOS 10.13

### ISSUE THREAD

**Issue by Bu11etmagnet** [clangd/vscode-clangd#228]
After starting vscode, a notification pops up that the clangd server crashed 5 times and will not be restarted.

**Logs**
I[11:14:42.517] clangd version 12.0.1 (https://github.com/llvm/llvm-project fed41342a82f5a3a9201819a82bf7a48313e296b)
I[11:14:42.518] PID: 85206
I[11:14:42.518] Working directory: /Users/csaba/wk/titan.eclipse
I[11:14:42.518] argv[0]: /Users/csaba/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/12.0.1/clangd_12.0.1/bin/clangd
I[11:14:42.518] Starting LSP over stdin/stdout
I[11:14:42.519] <-- initialize(0)
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/csaba/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/12.0.1/clangd_12.0.1/bin/clangd (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/csaba/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/12.0.1/clangd_12.0.1/bin/clangd (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/csaba/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/12.0.1/clangd_12.0.1/bin/clangd (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/csaba/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/12.0.1/clangd_12.0.1/bin/clangd (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

[Info  - 11:14:44 AM] Connection to server got closed. Server will restart.

**System information**
clangd version 12.0.1 (https://github.com/llvm/llvm-project fed41342a82f5a3a9201819a82bf7a48313e296b)
clangd extension version: 0.1.13
Operating system: macOS High Sierra 10.13.6

**Comment by kadircet** [comment]
Hi @Bu11etmagnet ! Can you try with one of our recent snapshot builds of clangd (for example https://github.com/clangd/clangd/releases/download/snapshot_20210905/clangd-mac-snapshot_20210905.zip). You can just unzip it to any folder and point vscode at the location of clangd inside the `bin` directory of the folder you've unzipped.

We normally set deployment target to MacOS 10.9, but there might've been an oversight while building the 12.0.1 release since it required some cherry-picks. If a more recent snapshot works, we should probably just rebuild the 12.0.1 release.
