### ISSUE TITLE
Editor context menu has the wrong "Switch Header/Source" item

### ISSUE THREAD

**Issue by vaivaswatha** [clangd/vscode-clangd#244]
After installing the vscode-clangd plugin and disabling `C_Cpp.intelliSenseEngine`, if I use `Alt+O`, I can switch b/w header and source files.

However, on the editor right-click (context) menu, the "Switch Header/Source" item is still bound to the function from `C_Cpp.intelliSenseEngine`, thus flagging an error that intellisense is disabled.

I tried locally adding a menu item in `package.json` of the vscode-clangd extension (just to see if that would work - not in the attached screenshot). That creates a new menu item for this operation and it works fine, but I can't figure out how to remove the menu entry that's already there and is incorrect.

**Logs**
![switch-source-header](https://user-images.githubusercontent.com/4222529/139634947-9bf29eb7-a3e8-4fef-98ce-a92c4bbf8386.png)

**System information**
Clangd version (from the log, or `clangd --version`): 13
clangd extension version: 0.1.13
Operating system: Linux / Ubuntu 20.04.

Related: 
- https://github.com/clangd/vscode-clangd/issues/182
- https://github.com/cquery-project/vscode-cquery/issues/48#issuecomment-414185582

**Comment by HighCommander4** [comment]
> I tried locally adding a menu item in `package.json` of the vscode-clangd extension (just to see if that would work - not in the attached screenshot). That creates a new menu item for this operation and it works fine,

Yes, we can add such a context menu item to vscode-clangd.

Would you like to submit a patch (since you've already done it locally)?

> but I can't figure out how to remove the menu entry that's already there and is incorrect

That menu item is contributed by the Microsoft extension. It can't be removed by vscode-clangd, nor (to my knowledge) via user config.

You could disable the Microsoft extension altogether, that should remove the menu item.

If you need to keep it enabled for some other reason, you could file an issue in [their repo](https://github.com/microsoft/vscode-cpptools/) asking to make the presence of that menu item conditional on `C_Cpp.intelliSenseEngine: true`.
