### ISSUE TITLE
Add option to disable color schema override

### ISSUE THREAD

**Issue by wcscmp** [clangd/vscode-clangd#28]
Latest update forces color schema overriding existing schema. It would be great to be able to disable this.

**Comment by hokein** [comment]
this is a feature of semantic highlighting, but by accident, we introduced a bug #27 in the latest release which makes it not respecting the color theme schema. should be fixed in #29. Sorry for the inconvenience.

until a new release, you can disable this feature by setting `"clangd.semanticHighlighting": false` in setting.json.

**Comment by sam-mccall** [comment]
Fixed in 0.1.5.

**Comment by dwlsalmeida** [comment]
Can this actually be implemented as a feature? I liked the previous color theme better. I even thought it was a bug when this was fixed in 0.1.5 (i.e. I thought semantic highlighting had stopped working, since it is so subtle with the default color theme)

An 'override' option would be great! :)
