### ISSUE TITLE
InlayHints are displayed even if disabled in settings

### ISSUE THREAD

**Issue by cleancodeline** [clangd/vscode-clangd#280]
I am using the latest clangd-14 and have noticed, that the inlayHints are now also displayed for C++. Great!

But sometimes I would like to disable them, so the true formatting of the file gets apparent again (aligned comments, etc.). 
I have not found a way to do this.  The official config setting seems to be ignored by vscode-clangd:

`"editor.inlayHints.enabled": false`

Also it would be nice to have a command, so inlayHints can been toggled quickly.

**Comment by sam-mccall** [comment]
Thanks, this is useful feedback!
- we should definitely add a client-side toggle to allow the workflow you mention. Probably a default keyboard shortcut too
- `editor.inlayhints.enabled` doesn't work because we're not using VSCode's inlay hints API to display them. So far this is a private API not available to third-party extensions. We'll switch when we can
- The current & future-proof way to configure this feature is to add `InlayHints: { Enabled: No }` to clangd's `config.yaml`. We'll have this documented shortly

**Comment by sam-mccall** [comment]
Maybe we can respect `editor.inlayhints.enabled` instead of adding our own setting for this under the clangd namespace...

**Comment by sam-mccall** [comment]
I haven't added a command for now, since we don't "own" the setting we'd be toggling.

I'd suggest https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler as a workaround.
See also https://github.com/microsoft/vscode/issues/128162
