### ISSUE TITLE
Clangd replaces `func` with `__func__`

### ISSUE THREAD

**Issue by Volker-Weissmann** [clangd/vscode-clangd#356]
If I open `main.c` with the content
```
int main() {}
```
, place the cursor between the curly brakets and press the keys "func(", this text appears:
```
int main() {__func__()}
```
The "__" do not belong there.

**Logs**
[1-clangd.log](https://github.com/clangd/vscode-clangd/files/9084392/1-clangd.log)

**System information**
```
$ clang --version
clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
clangd extension version: v0.1.18
Operating system: Arch Linux

**Comment by sam-mccall** [comment]
`__func__` is a magic variable [available within functions](https://en.cppreference.com/w/cpp/language/function) and seems like a reasonable code completion suggestion. If a function `func` exists it should be ranked higher.

The "replacement" behavior occurs because vscode:
 - treats `(` as an accept character
 - implicitly selects the first item in the list

The former is intended, I think the latter is your problem? It's https://github.com/microsoft/vscode/issues/139825 (and many previous reports, they seem reluctant to change it). In any case, this is VSCode behavior :-(

(I was initially unable to reproduce this problem because the vscodevim extension disables this behavior, but that's not a good general-purpose workaround)

**Comment by sam-mccall** [comment]
If I open `test.js` and type `F(` VSCode will complete as `File(`.

**Comment by Volker-Weissmann** [comment]
Ok

**Comment by Volker-Weissmann** [comment]
> Huh. I use vscode, and I neither get completion auto-activated when I type identifier characters (I have to press Ctrl+Enter, or type `.` or `->` to activate member completion), nor does pressing `(` accept the first proposal (only Enter or Tab does that). I wonder what I have configured differently from you.

I got a nearly clean config.

**Comment by sam-mccall** [comment]
@HighCommander4 that sounds like `"editor.quickSuggestions.other": "off"`

I think "quick suggestions" means trigger in text-like context ("other"=identifiers, comments/strings are also valid there), as opposed to "trigger characters" which is `.`, `>` etc.

**Comment by sam-mccall** [comment]
There *is* some interaction with recent changes here: commit characters weren't being respected with vscode-clangd 0.1.17 but are in 0.1.18. This is due to upgrading to v8 of microsoft's language client - i.e. this is still a deliberate VSCode change (which is why it shows up in the python extension too).

**Comment by sam-mccall** [comment]
Yeah this is indeed new behavior, albeit mostly intended by VSCode devs.
I think the overall experience is broken enough that we ended up restoring the behavior (and subverting VSCode's intentions) in 0.1.20.

https://github.com/clangd/vscode-clangd/issues/357 is basically a dupe of this report, where we managed to get to the bottom of the behavior, sorry for closing prematurely.
