### ISSUE TITLE
Parameter inlays have gotten a bit absurd with stuff like gtest

### ISSUE THREAD

**Issue by dmurph** [clangd/vscode-clangd#385]
I'm not sure if there's a solution here, but when using gtest/gmock, it looks like this:
<img width="923" alt="Screen Shot 2022-10-07 at 2 35 58 PM" src="https://user-images.githubusercontent.com/294026/194661884-959adcc9-5045-4e29-be6f-c3f71e990c10.png">

**Comment by HighCommander4** [comment]
Could you specify which clangd version you're testing with? I use gtest in one of my projects and, with clangd 15.0.2, I do not get any parameter hints in or around an `EXPECT_EQ` (the `lhs` and `rhs` would actually be useful, even more so if renamed to `expected` and `actual` since I always forget the order of "expected" and "actual" in assertions; the ones at the beginning are obviously undesirable).

**Comment by dmurph** [comment]
I'm at trunk, currently at commit 4b1833d7d98e07e3b43d1265c86e9ed8d457e0f2

**Comment by sam-mccall** [comment]
> I'm at trunk, currently at commit 4b1833d7d98e07e3b43d1265c86e9ed8d457e0f2

It's actually fixed at 67268ee11c220b1dfdf84afb10a12371c5ae6400 (a couple of days ago), if you sync and rebuild it should be gone (the ones outside the macros that is).

(For anyone else seeing this, not even our unstable snapshots have the fix yet.
https://github.com/clangd/clangd/releases - there should be one stamped 20221009 in a couple of days.)

Maybe we should get that patch cherrypicked. It's pretty complicated though :-\

**Comment by sam-mccall** [comment]
The original bug was https://github.com/clangd/clangd/issues/1289

**Comment by dmurph** [comment]
Nice! Thanks for following up. Excited to get the fix soon :) just disabled the inlays for now.
