### ISSUE TITLE
Any way to disable automatic addition of `#include`s?

### ISSUE THREAD

**Issue by crayzeewulf** [clangd/vscode-clangd#4]
This extension automatically adds `#include` directives "where needed". However, in some cases one may not want this (for example, with forward declarations). Is there a way to disable this feature completely?

**Comment by sam-mccall** [comment]
Yes: the flag `-header-insertion=never`. (You can configure clangd arguments in the preferences).

It should already be suppressed if there's a forward declaration in the current file, so please file a bug if you see that.

There's a feature request for a less-aggressive insertion policy (vs current include-what-you-use) but it's not currently being worked on.

**Comment by jhasse** [comment]
> It should already be suppressed if there's a forward declaration in the current file, so please file a bug if you see that.

Against clangd or here?

What I often run into is writing a forward declaration. So 
```
class FooB<TAB>
```
adds
```
#include "FooBar.hpp"
```
.

Due to the aggressiveness of the insertion, what do you think about making `-header-insertion=never` the default?

**Comment by HighCommander4** [comment]
> > It should already be suppressed if there's a forward declaration in the current file, so please file a bug if you see that.
> 
> Against clangd or here?

clangd, as changing the behaviour for the mention example would be a server-side change.

**Comment by lakshits11** [comment]
> Yes: the flag `-header-insertion=never`. (You can configure clangd arguments in the preferences).
> 
> It should already be suppressed if there's a forward declaration in the current file, so please file a bug if you see that.
> 
> There's a feature request for a less-aggressive insertion policy (vs current include-what-you-use) but it's not currently being worked on.

Hello I am using Sublime Text and LSP plugin. Where to include this line in my project and how ( I mean do I have to make any new file for it . I know nothing about it so please help)..

**Comment by kadircet** [comment]
You should probably use the communication channels of your editor/plugin instead, as we don't provide the integration/support for those. I did a little digging you might want to take a look at https://lsp.sublimetext.io/guides/client_configuration/ and `command` parameter specifically.

**Comment by jinastro** [comment]
> 

you could add a .clangd file and add a line like this
```
header-insertion: never
```

**Comment by HighCommander4** [comment]
> you could add a .clangd file and add a line like this
> 
> ```
> header-insertion: never
> ```

No, this option cannot be specified in the config file. The list of supported config file keys is documented at https://clangd.llvm.org/config.html; there isn't an automatic mapping from command-line options to config keys (in fact they're mostly disjoint sets of options).

**Comment by masayuki-nakano** [comment]
I'm sometimes in trouble due to this.

* When I add some code for debugging or tying, automatically some header files included, but even after I remove the code, the automatically added includes are not removed automatically, and of course, I don't realize the include changes because of silently done.
* If the file has specific order rules of inclusion, it's not followed by the plugin, of course.

**Comment by HighCommander4** [comment]
>    * When I add some code for debugging or tying, automatically some header files included, but even after I remove the code, the automatically added includes are not removed automatically, and of course, I don't realize the include changes because of silently done.

Clangd does provide warnings for unused includes, perhaps this helps?

Do you have any other suggestions for what clangd could do to mitigate this (besides the already-existing option to disable header insertion altogether)?
 
>    * If the file has specific order rules of inclusion, it's not followed by the plugin, of course.

The header insertion tries to respect the clang-format include style as specified in the `IncludeBlocks` and `IncludeCategories` [style options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).

**Comment by zrno** [comment]
> Do you have any other suggestions for what clangd could do to mitigate this (besides the already-existing option to disable header insertion altogether)?

In my case, all the files I am using have something at the top of the file. Maybe some debug macros, maybe some copyright header and the includes come only after that. I would like if the new include was somehow added into the group of includes and not at the top of the file.

**Comment by HighCommander4** [comment]
> > Do you have any other suggestions for what clangd could do to mitigate this (besides the already-existing option to disable header insertion altogether)?
> 
> In my case, all the files I am using have something at the top of the file. Maybe some debug macros, maybe some copyright header and the includes come only after that. I would like if the new include was somehow added into the group of includes and not at the top of the file.

Could you give a concrete example?

**Comment by masayuki-nakano** [comment]
> > * When I add some code for debugging or tying, automatically some header files included, but even after I remove the code, the automatically added includes are not removed automatically, and of course, I don't realize the include changes because of silently done.
> 
> Clangd does provide warnings for unused includes, perhaps this helps?

No, I don't see such warning, and I don't usually check what I've not touched because I don't think new errors may happen where I didn't touch.

> Do you have any other suggestions for what clangd could do to mitigate this (besides the already-existing option to disable header insertion altogether)?

My most unpleasant point is, the insertion is done **silently**. Therefore, just suggesting/asking whether the inclusion is required could be better.

> > * If the file has specific order rules of inclusion, it's not followed by the plugin, of course.
> 
> The header insertion tries to respect the clang-format include style as specified in the `IncludeBlocks` and `IncludeCategories` [style options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).

In my case, there are some blocks of inclusions. First one is for the header files which has declaration of classes/structs to be implemented in the cpp file.  The others are, a group of local header files in the module, a group of project/product global header files, a group of header files whose names are legacy ones in the project, a group of header files coming from external project, etc. This could be fixable with the options, but I have no idea why I need to work on such things for what I don't want to use.

Additionally, another problem is, it includes headers too aggressively. E.g., there may be a header file which only includes some other headers to make it easier to use. Even if a cpp file includes it and the writing things are already available in the file, the low level header may be included again. This makes headers which should be hidden in most files appear in most files. Therefore, I think that appending inclusion should work only when newly used thing causes a compile error.

**Comment by HighCommander4** [comment]
> My most unpleasant point is, the insertion is done **silently**. Therefore, just suggesting/asking whether the inclusion is required could be better.

Interesting idea. One way this could be implemented in terms of existing functionality in the Language Server Protocol would be to compute the include insertion but not perform it together with the completion, but instead, if the completion results in a new diagnostic (due to the missing include), then attach it as a quick fix to the diagnostic.

> This could be fixable with the options, but I have no idea why I need to work on such things for what I don't want to use.

I mentioned this above, but just to make sure you haven't overlooked it: we have the existing command-line flag `--header-insertion=never` which disables header insertion altogether.

> Additionally, another problem is, it includes headers too aggressively. E.g., there may be a header file which only includes some other headers to make it easier to use. Even if a cpp file includes it and the writing things are already available in the file, the low level header may be included again. This makes headers which should be hidden in most files appear in most files. Therefore, I think that appending inclusion should work only when newly used thing causes a compile error.

The header insertion feature is based on the principle of ["include what you use"](https://include-what-you-use.org/) (IWYU), meaning if a file uses a symbol, it should include the file declaring that symbol directly.

So, there are a couple of possibilities here:

  1. The codebase's code style does not try to follow IWYU at all. In this case, the header insertion feature in its current form is probably not a good fit for the codebase and it's better to disable it. It would be technically possible to implement a new mode for header insertion which behaves in the way you describe. (The "quick fix" idea suggested above would accomplish something similar.)

  2. The codebase's code style generally does try to follow IWYU, but there are some exceptions, e.g. some "private" headers which should not be included directly but instead through an umbrella header. In this case, the exceptions can be marked using [annotations](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md) which clangd aspires to follow (the implementation of this is a work in progress, e.g. I believe clangd currently supports `IWYU pragma: private` but not yet `IWYU pragma: export`; the latter is tracked in https://github.com/clangd/clangd/issues/1085).

**Comment by masayuki-nakano** [comment]
I met another trouble. While I'm editing an header file, this feature automatically includes another header file which depends on the header file instead of adding forward declaration. Therefore, I struggled with odd compile errors because I didn't realize the auto inclusion...

**Comment by HighCommander4** [comment]
> > Therefore, I think that appending inclusion should work only when newly used thing causes a compile error.
> 
> [...] It would be technically possible to implement a new mode for header insertion which behaves in the way you describe.

I did overlook at the time, that we have https://github.com/clangd/clangd/issues/70 open for this.

**Comment by ethanc8** [comment]
clangd doesn't seem to recognize things that are imported via #import.

**Comment by qiyuewuyi2333** [comment]
May be try `--header-insertion=never`, I add `-header-insertion=never` (just one -) firstly, but it doesn't work.

**Comment by teleprint-me** [comment]
I just create a `.clangd` file in the CWD and copy-paste the following.

```clang
CompileFlags:
  Add: [-ferror-limit=0, -header-insertion=never, -xc, -I./include]
```

That's it. The [docs](https://clangd.llvm.org/config.html#headerinsertion) state that you can use inline comments as well.

I'll add feedback if this doesn't work.

This should be **disabled** by default and be an explicit opt-in feature instead. I have no idea why this is enabled out of the box. Seems more like a clangd issue than a plugin specific issue.
