### ISSUE TITLE
The diagnostics do not take into account unsaved changes

### ISSUE THREAD

**Issue by Shatur95** [clangd/vscode-clangd#60]
**Steps to reproduce**

1. Open any class
2. Create a member function for it with any name / parameters
3. Open .cpp file
4. Create any **correct** implementation of the previously created function.

**Expected behavior**

Diagnostics say that everything is okay.

**Current behavior**

Diagnostics say that such function does not exits until saving header.

**System information**

Output of `clangd --version`: 10.0.1
clangd extension version: v0.1.6
Operating system: Arch Linux

**Notes**

It works correctly in `QtCreator` that use `clangd` for diagnostics.

**Comment by kadircet** [comment]
yes that's the model we have in clangd. dirty buffer contents are only used for main file, includes are read from disk.

**Comment by Shatur95** [comment]
Should I report this in `clangd` instead? This is very inconvenient behavior and I do not see any case when could it be useful.

**Comment by kadircet** [comment]
>Should I report this in clangd instead?

sure, let me transfer the issue for you. but as i'll try to explain below, i don't think the outcome will change.

> This is very inconvenient behavior and I do not see any case when it could be useful.

clangd tries to reflect the state of the real build as much as possible. hence we always make use of the file state on disk rather than your editor, the only exception is the main file and it is deliberately done to provide you with diagnostics as you type and all the other features (hover, go-to-def, refs, etc.) for the code you've just written.

using on-disk state for headers also means we can get changes done outside your editor. e.g. due to an operation like `git pull` files can change underneath your editor, and if we were not to use the disk state, half of your headers might reflect the state in the editor and the rest would show on disk, it makes everything a lot harder to reason about. there are a couple more similar arguments for the reason we use on-disk state for headers.

I can also see how this doesn't work with some workflows (e.g. the one you described) but our experience has so far indicated that majority of the users are ok with this trade-off we made.

Sorry for closing the issue without explaining why, hope that sheds some light.
