### ISSUE TITLE
active macros greyed out

### ISSUE THREAD

**Issue by k4lizen** [clangd/vscode-clangd#671]
**Please describe the problem.**
Im reading the source code of glibc and some important parts are greyed out. e.g.
![image](https://github.com/user-attachments/assets/7005b8ef-6bb1-451a-92ba-a7899c982d4a)
I'm not sure where vscode-clangd pulls the value of `USE_TCACHE` from, but in practice it's always active and encapsulates a large and important part of the codebase.

If it's not possible for these values to be correctly resolved is it possible for me to turn off this feature (of "inactive" macros being grayed out), or hint to the extension that some value is actually active?

**System information**
Clangd version (from the log, or `clangd --version`): 18.1.8
clangd extension version: v0.1.29
Operating system: artix linux

**Comment by k4lizen** [comment]
Nevermind I'm blind, found it.
![image](https://github.com/user-attachments/assets/477f4a77-7f6a-42fe-a48e-1505c7702bfa)

**Comment by HighCommander4** [comment]
Note that while adjusting the setting you found will get inactive preprocessor regions to be displayed at full opacity, semantic features (such as go-to-definition) will still not work inside such regions.

I would suggest instead following the instructions at https://clangd.llvm.org/installation#project-setup to configure the project so that the correct branches are active.

**Comment by k4lizen** [comment]
kay, thanks!
