### ISSUE TITLE
do not support  windows remote host

### ISSUE THREAD

**Issue by Titan-p** [clangd/vscode-clangd#75]
I tried to connect to a remote ssh host(windows).  
Clangd Path is set to "C:\Program Files\LLVM\bin\clangd.exe" which exists.

**Logs**
After execute "manually active clangd extension".
It shows "Command 'Manually activate clangd extension' resulted in an error (command 'clangd.activate' not found)".

**System information**
Clangd version (from the log, or `clangd --version`): 10.0.0
clangd extension version: 0.1.7
Operating system: Windows 10(remote host windows 10)

**Comment by hokein** [comment]
Can you explain why you execute the "manually active clangd extension" command? if you open a normal c++ file, the extension is auto activated, so you don't need to trigger that command.

The "manually active clangd extension" is a rarely-used command  -- we introduced that because the extension did not auto start with a `.cu` file, I think we fix that now, we should remove this command.

**Comment by Titan-p** [comment]
> Can you explain why you execute the "manually active clangd extension" command? if you open a normal c++ file, the extension is auto activated, so you don't need to trigger that command.
> 
> The "manually active clangd extension" is a rarely-used command -- we introduced that because the extension did not auto start with a `.cu` file, I think we fix that now, we should remove this command.

Because I didn't see any clang language server output. So I thought the extension didn't activated properly.
The extension works fine now after a total vs-code restart.
This issue could be closed. Thanks for your reply.
