### ISSUE TITLE
Command 'clangd.restart' tries to re-register 'clangd.memoryUsage'?

### ISSUE THREAD

**Issue by makestuff** [clangd/vscode-clangd#95]
I wanted to try out the "watch `compile_commands.json`" enhancement added by #33, so I cloned to commit 0b171de, and tried it on Debian 10.4 with VSCode 1.51.0 and clangd 11.0.1 installed from the "llvm-toolchain-buster-11" repository.

Changes to `compile_commands.json` result in a pop-up, as expected, but when I select "restart", the `clangd` process exits but silently fails to restart, with no hints in the "Clangd Language Server" log. Further investigation revealed it to be a problem with the "clangd.restart" command itself: in the v0.1.7 release, this works fine, but in commit 0b171de it produces this error:

`Command 'Restart the clangd language server' resulted in an error (command 'clangd.memoryUsage' already exists)`

I could hackily make this error go away and get the behaviour intended by #33 by commenting out the lines in `out/src/memory-usage.js`:

`vscode.commands.registerCommand('clangd.memoryUsage', ...);`
`vscode.commands.registerCommand('clangd.memoryUsage.close', ...);`

I suspect you just need to check whether that command has already been registered, but my TypeScript knowledge is almost nonexistent so I'm not going to embarrass myself by raising a PR for it!

**Comment by HighCommander4** [comment]
Thanks for reporting, sounds like a regression from #86.

**Comment by HighCommander4** [comment]
Based on our other usages of `registerCommand()`, the issue seems to be that we are not saving the `Disposable` returned by that function (which un-registers the command).

I believe the intended behaviour is:
  * the restart command calls [`clangdContext.dispose()`](https://github.com/clangd/vscode-clangd/blob/0b171de763c935d726a5555392b292a3f5f81940/src/extension.ts#L23), which should result in commands being un-registered
 * the restart command then calls  [`clangdContext.activate()`](https://github.com/clangd/vscode-clangd/blob/0b171de763c935d726a5555392b292a3f5f81940/src/extension.ts#L24) which should result in commands being re-registered

Other calls to `registerCommand()` like [this one](https://github.com/clangd/vscode-clangd/blob/0b171de763c935d726a5555392b292a3f5f81940/src/switch-source-header.ts#L7) add the result to `context.subscriptions` (which is a list of things that `clangdContext.dispose()` will go through and dispose each one), so we should probably be doing the same thing for `clangd.memoryUsage`.
